export const FEATURE_FLAGS = {
  ENABLE_WHITEBOARD: true,
  ENABLE_KANBAN: true,
  ENABLE_SUBSCRIPTION: true,
  MAX_UPLOAD_SIZE: 500 * 1024 * 1024, // 500MB
  MAX_TRANSCRIPT_LENGTH: 10000,
} as const;
